hcp_hostname = "app.terraform.io"
organization = "poc-itau-org"

workspace "your-workspace" {
  working_directory = "./"

  source_backend "s3" {
    bucket = "terraform-pipeline-itau"
    key    = "terraform.tfstate"
    region = "us-east-2"
  }
}
