workspace = [{
  name = "itau-pipeline-workspace"
  working_directory = "./"
  organization = "poc-itau-org"

  source_backend = {
    name = "s3"
    bucket = "terraform-pipeline-itau"
    key    = "terraform.tfstate"
    region = "us-east-2"
  }
}]
