organization = "poc-itau-org"
workspace "itau-pipeline-workspace" {
  working_directory = "./"

  source_backend "s3" {
    bucket = "terraform-pipeline-itau"
    key    = "terraform.tfstate"
    region = "us-east-2"
  }
}
